### ISSUE TITLE
🚨 Verification Scripts Fail

### ISSUE THREAD

**Issue by abigger87** [abigger87/femplate#12]
## Overview

Verification scripts fail due to `Invalid Compiler Version`

Ex:
```
Invalid compiler version. See https://etherscan.io/solcversions for list of supported solc versions
```

**Comment by zkSoju** [comment]
Apparently for this you have to paste the specific version from https://etherscan.io/solcversions

`0.8.11` is `v0.8.12+commit.f00d7308`

**Comment by zkSoju** [comment]
Nevermind totally missed that you were going to parse dynamically.
