### ISSUE TITLE
messing up with rinkeby deployment script is easy

### ISSUE THREAD

**Issue by TimDaub** [abigger87/femplate#24]
- https://github.com/abigger87/femplate/blob/master/scripts/deploy.sh
- https://github.com/abigger87/femplate/blob/master/scripts/deploy_rinkeby.sh
- these both files are very similar and so if a user e.g. accidentally puts a mainnet RPC endpoint into deploy_rinkeby.sh there's a good chance that a contract on mainnet will be deployed.
- So why in the first place are there two separate scripts? Or if the rinkeby script is useful, can we make it such that a contract never ends on mainnet (e.g. that the script fails if a rpc endpoint with a chainId other than rinkeby gets pasted by the user)

**Comment by abigger87** [comment]
Removed
